### ISSUE TITLE
Overworld and Skyblock

### ISSUE THREAD

**Issue by Tkhakiro** [MarkusBordihn/BOs-Lobby#7]
Good afternoon. Your mod is very interesting. Could you realize the desire of many: worlds for fishing and other things, replace with a skyblock. As a result, I will finally be able to play on a local network with my girlfriend (she hates skyblock).

For example, it would look like this: 
1) When entering the world, players appear in the normal world, then through command, players can move to Skyblock (with their biomes + with his Nether). 
2) So that the ordinary world and the Skyblock world have their own Nether when using a standard portal. 
3) You also need the ability to build a portal connecting overworld and skyblock (for example, it will work only when two portals are activated on different sides and there can only be one such portal, one in overworld and one in skyblock, the previous ones will be disabled).

As an example, you can take Skyblock 4.10 as a basis, since there are all the main structures and biomes that are relevant at the moment.

For simplicity and faster communication, we can write off via discord. Тхакиро Левиафан#5845

P.s. I used google translator to write my idea, if something is not clear, I will try to put it in a different way.

**Comment by MarkusBordihn** [comment]
Thanks for the idea, unfortunately this is nothing which could be easily implemented.

I could easily add an additional dimension for Skyblock, but I'm not able to add an seperated nether for this dimension.
Your idea would need a deeper modification of the portal blocks and the skyblock system, which is out of scope of this mod.

I recommend to ask a SkyBlock Mod Pack Builder if they see any way to create such a mod pack for an single Minecraft instance.

In general for such a setup it would be easier to use BungeeCord and Mohist to connect two servers (one normal + one with skyblock) instead of trying to run everything on a single one.
