### ISSUE TITLE
mining dimension has overworld

### ISSUE THREAD

**Issue by MoonMoonShark** [MarkusBordihn/BOs-Lobby#9]
**Describe the bug**
the mining dimension is not "build limit to build limit" underground, but rather a duplication of the overworld, with its own overworld.  this is causing issues with teleportation where players end up on the overworld above the mining dimension.

**To Reproduce**
1. Go to 'mining dimension'
2. Use FTB Essentials "/rtp"
3. End up in new part of mining overworld, not in cave.

Alternate steps to reproduce the behavior:
1. Set Waystones mod "warp plate" at location in overworld
2. Go to mining dimension
3. Set second Waystones mod "warp plate" at location in mining dimension
4. Use warp plate in mining dimension to return to warp plate in overworld (works)
5. Use warp plate in overworld to return to mining dimension (results in going to the same location, but overworld elevation)

**Expected behavior**
Expected mining dimension to be "bedrock to build limit" underground with no overworld

**Screenshots**

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Currently included in The Lighthouse modpack
https://www.curseforge.com/minecraft/modpacks/the-lighthouse

**Additional context**
additionally, when i try to remove the mod from my server, the world can't start back up, throwing an error about missing lobby:void_dimension.

**Comment by MarkusBordihn** [comment]
Thanks for the report.

**Mining dimension has an overworld**
Unfortunately this is by design to support as much as possible mods in this dimension.
There are mods which spawning their ores or resources in the over-world and even Minecraft itself is spawning diamonds in mountains. 
See: https://twitter.com/henrikkniberg/status/1465721712973164544

You have always the option to customize your mining dimension and make it full "bedrock" over data-packs.
See: https://github.com/MarkusBordihn/BOs-Lobby#customization

There are generator like https://misode.github.io/ which simplify this.

**Not loading world**
New dimension will be added over data-pack, as soon you remove the mod, the data-packs are removed as well.
This means if you want to restort an old world you need to remove all reference to the dimensions and former data-packs otherwise Minecraft is unable to load them.

That's the reason why I added the following note to the mod **Note: Please make sure to create regular backups of your dimensions, before installing or updating this mod.**

**Comment by MoonMoonShark** [comment]
excellent. i'll see what i can do to figure out how to add a datapack to make the mining dimension be "floor to ceiling" and "wall to wall" mines. thank you!
